project_id = "eyfrwfhkenuwrkccmqle"

[functions.analyze-meeting]
verify_jwt = false

[functions.google-auth]
verify_jwt = false

[functions.google-auth-callback]
verify_jwt = false

[functions.send-gmail]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false
